package com.javen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSysuid(java.lang.Integer sysuid) {
		set("sysuid", sysuid);
	}

	public java.lang.Integer getSysuid() {
		return get("sysuid");
	}

	public void setAppId(java.lang.String appId) {
		set("appId", appId);
	}

	public java.lang.String getAppId() {
		return get("appId");
	}

	public void setAppSecret(java.lang.String appSecret) {
		set("appSecret", appSecret);
	}

	public java.lang.String getAppSecret() {
		return get("appSecret");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setEncryptMessage(java.lang.Boolean encryptMessage) {
		set("encryptMessage", encryptMessage);
	}

	public java.lang.Boolean getEncryptMessage() {
		return get("encryptMessage");
	}

	public void setEncodingAesKey(java.lang.String encodingAesKey) {
		set("encodingAesKey", encodingAesKey);
	}

	public java.lang.String getEncodingAesKey() {
		return get("encodingAesKey");
	}

	public void setMchId(java.lang.String mchId) {
		set("mchId", mchId);
	}

	public java.lang.String getMchId() {
		return get("mchId");
	}

	public void setPaternerKey(java.lang.String paternerKey) {
		set("paternerKey", paternerKey);
	}

	public java.lang.String getPaternerKey() {
		return get("paternerKey");
	}

	public void setCertPath(java.lang.String certPath) {
		set("certPath", certPath);
	}

	public java.lang.String getCertPath() {
		return get("certPath");
	}

	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}

	public java.lang.String getDomain() {
		return get("domain");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setCreatTime(java.util.Date creatTime) {
		set("creatTime", creatTime);
	}

	public java.util.Date getCreatTime() {
		return get("creatTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setRemake(java.lang.String remake) {
		set("remake", remake);
	}

	public java.lang.String getRemake() {
		return get("remake");
	}

}
