package com.javen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKeyword<M extends BaseKeyword<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAppId(java.lang.String appId) {
		set("appId", appId);
	}

	public java.lang.String getAppId() {
		return get("appId");
	}

	public void setReplyType(java.lang.Integer replyType) {
		set("replyType", replyType);
	}

	public java.lang.Integer getReplyType() {
		return get("replyType");
	}

	public void setKeyWord(java.lang.String keyWord) {
		set("keyWord", keyWord);
	}

	public java.lang.String getKeyWord() {
		return get("keyWord");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setRemake(java.lang.String remake) {
		set("remake", remake);
	}

	public java.lang.String getRemake() {
		return get("remake");
	}

}
