package com.javen.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("wx_articles", "id", Articles.class);
		arp.addMapping("wx_config", "id", Config.class);
		arp.addMapping("wx_keyword", "id", Keyword.class);
		arp.addMapping("wx_subscription", "id", Subscription.class);
		arp.addMapping("wx_user", "id", User.class);
	}
}

