package com.javen.model;

import com.javen.model.base.BaseKeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Keyword extends BaseKeyword<Keyword> {
	public static final Keyword dao = new Keyword().dao();
	
	public static final String TABLE_NAME = "wx_keyword";


	public Keyword findKeyWord(int configId, String msgContent) {
		return findFirst("select * from "+ TABLE_NAME +" where configId=? and content=?",configId,msgContent);
	}
}
