package com.javen.model;

import com.javen.model.base.BaseSubscription;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subscription extends BaseSubscription<Subscription> {
	public static final Subscription dao = new Subscription().dao();
}
